server:
  port: 9041

spring:
  application:
    name: hc-server-system
  profiles:
    active: dev
  cloud:
    #配置中心
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: hc-config
    nacos:
      discovery:
        server-addr: ${nacos.url}:9010
  boot:
    admin:
      client:
        url: http://localhost:9060
        username: sonake
        password: 123456
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 47.105.40.52
    port: 5672
    username: guest
    password: guest
  datasource:
    dynamic:
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: HcHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: Jdkc0912..
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.105.40.52:3306/sonake?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
mybatis-plus:
  type-aliases-package: com.hc.common.bean.system
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

hc:
  server:
    system:
      basePackage: com.hc.server.system.controller
      title: Hc-Server-System API
      description: Hc-System-System API
      version: 1.0
      author: Sonake
      url: https://www.sonake.com
      email: 760946378@qq.com
      license: Apache 2.0
      licenseUrl: https://www:apache.org/licenses/LICENSE-2.0.html
      anonUrl: /swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**
      grantUrl: http://${hc-gateway}:9030/auth/oauth/token
      name: hc_oauth_swagger
      scope: test

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:9030/auth/user