# mysql
spring:
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #MySQL����
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://47.105.40.52:3306/sonake?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #username: root
    #password: Jdkc0912..
    #oracle����
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: renren
    #    password: 123456
    #SQLServer����
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    #PostgreSQL����
    #    driverClassName: org.postgresql.Driver
    #    url: jdbc:postgresql://192.168.10.10:5432/renren_fast
    #    username: postgres
    #    password: 123456
    url: jdbc:mysql://47.105.40.52:3306/sonake?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Jdkc0912..
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  type-aliases-package: com.hc.admim.bean
  global-config:
    banner: false


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#ָ�����ݿ⣬��ѡֵ�С�mysql��oracle��sqlserver��postgresql��
renren:
  database: mysql
#�Զ�������
hc:
  shiro:
    #��λ��
    tokenTimeOut: 3600
    # �������֤�ӿ� url
    anonUrl: /login,/logout/**,/regist,/user/check/**
server:
  port: 8081
